### ISSUE TITLE
Falied Install on Windows 

### ISSUE THREAD

**Issue by RoboticMind** [rsparlin/Gridcoin-Web-Client#1]
When I run the command `npm run build-prod` here is the output:

> \> GridcoinWebClient@0.1.0 build-prod [REDACTED]
> \> NODE_ENV=production webpack
> 
> 'NODE_ENV' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! GridcoinWebClient@0.1.0 build-prod: \`NODE_ENV=production webpack\`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the GridcoinWebClient@0.1.0 build-prod script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I cannot get the Gridcoin-Web-Client to properly install on Windows

**Comment by rsparlin** [comment]
Hi RoboticMind,

Windows does not accept the syntax used by Bash for setting environment variables, which is why this is failing. I was able to build on windows by running the following commands:
```
> set NODE_ENV=production
> .\node_modules\.bin\webpack
```
To run it, you can use the same syntax:
```
> set NODE_ENV=production
> set GWC_PORT=8080
> set GWC_HOST=127.0.0.1
> node src\server.js
```
I'll update the readme with this information.
